/**
 * Commander SSO Landing Page - /auth/sso
 *
 * This page receives the one-time SSO token generated by
 * smarter.poker/api/auth/commander-sso and completes the cross-origin login.
 *
 * Flow:
 *   1. smarter.poker hub redirects here with ?token=<raw>&uid=<userId>
 *   2. This page calls /api/auth/sso-exchange with the token + uid
 *   3. The exchange API verifies hash, marks token used, returns a Supabase
 *      magic-link / custom token that setSession() can consume.
 *   4. completeLogin() stores commander_staff + commander_venue in localStorage.
 *   5. Redirect to /commander/dashboard.
 *
 * Security notes:
 *   - Token is single-use (marked used=true in DB on first exchange)
 *   - Token TTL is 60 seconds - stale URLs silently fail
 *   - No sensitive data is in the URL except the random token (no JWT)
 */
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { Loader2, ShieldCheck, AlertTriangle } from 'lucide-react';
import { supabase } from '../../src/lib/supabase';
import SEOHead from '../../src/components/seo/SEOHead';

export default function SSOPage() {
  const router = useRouter();
  const [status, setStatus] = useState('loading'); // 'loading' | 'error' | 'success'
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!router.isReady) return;
    const { token, uid } = router.query;

    if (!token || !uid) {
      setError('Invalid SSO link. Please sign in manually.');
      setStatus('error');
      return;
    }

    async function exchangeToken() {
      try {
        // Exchange the one-time token for a Supabase session
        const res = await fetch('/api/auth/sso-exchange', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ token, uid }),
        });

        const data = await res.json().catch(() => ({}));

        if (!res.ok || !data.token) {
          setError(data.error || 'SSO failed. The link may have expired. Please sign in again.');
          setStatus('error');
          return;
        }

        // Verify the OTP (magic-link type) to get a real Supabase session
        const { data: sessionData, error: otpError } = await supabase.auth.verifyOtp({
          email: data.email,
          token: data.token,
          type: data.type || 'magiclink',
        });

        if (otpError || !sessionData?.session) {
          setError('Failed to restore session. Please sign in manually.');
          setStatus('error');
          return;
        }

        const user = sessionData.session.user;
        const accessToken = sessionData.session.access_token;

        if (!user) {
          setError('Session could not be verified. Please sign in manually.');
          setStatus('error');
          return;
        }

        // Now run the same subscription check + staff session storage as the login page
        await completeCommanderLogin(user, accessToken);
        setStatus('success');
      } catch (err) {
        console.error('[SSO] Exchange error:', err);
        setError('An error occurred during sign-in. Please try again.');
        setStatus('error');
      }
    }

    exchangeToken();
  }, [router.isReady, router.query]); // eslint-disable-line react-hooks/exhaustive-deps

  /**
   * Mirrors the completeLogin() function in commander/login.js -
   * checks subscription and stores commander_staff, commander_venue,
   * commander_subscription in localStorage, then redirects to dashboard.
   */
  async function completeCommanderLogin(user, accessToken) {
    const abortController = new AbortController();
    const fetchTimeout = setTimeout(() => abortController.abort(), 15000);

    // Multi-club support: pass the last venue the user switched to (set by
    // the hamburger club switcher) so SSO login restores that club, not just
    // the newest subscription. Server validates ownership.
    let preferredVenueId = null;
    try { preferredVenueId = localStorage.getItem('commander_active_venue_id') || null; } catch { /* ignore */ }

    const subRes = await fetch('/api/commander/check-subscription', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${accessToken}`,
      },
      body: JSON.stringify({ userId: user.id, preferred_venue_id: preferredVenueId }),
      signal: abortController.signal,
    });
    clearTimeout(fetchTimeout);

    const subData = await subRes.json().catch(() => ({}));

    if (!subRes.ok || !subData.subscription) {
      setError(
        subData.error ||
        'No active Club Commander subscription found for this account. Please sign up.'
      );
      setStatus('error');
      return;
    }

    const subscription = subData.subscription;

    localStorage.setItem('commander_venue', JSON.stringify(subscription.venue));
    localStorage.setItem('commander_subscription', JSON.stringify(subscription));

    const staffSession = {
      ...(subData.staff_session || {
        user_id: user.id,
        role: 'owner',
        venue_id: subscription.venue_id,
      }),
      email: user.email,
      display_name:
        subscription.billing_name ||
        user.user_metadata?.full_name ||
        user.user_metadata?.name ||
        user.email,
      venue_name: subscription.venue?.name || 'My Venue',
      permissions: {
        manage_games: true,
        manage_waitlist: true,
        manage_staff: true,
        manage_tables: true,
        manage_tournaments: true,
        manage_settings: true,
        view_analytics: true,
        view_reports: true,
        send_announcements: true,
      },
    };
    localStorage.setItem('commander_staff', JSON.stringify(staffSession));
    localStorage.setItem('commander_remember', 'true');
    // Drop any previous user's cached club/home-game switcher list
    try { sessionStorage.removeItem('commander_accounts_cache'); } catch { /* ignore */ }

    // Redirect to dashboard (or stored return URL)
    let redirectTo = '/commander/dashboard';
    try {
      const returnUrl = sessionStorage.getItem('commander_return_url');
      if (returnUrl && returnUrl.startsWith('/commander/')) {
        redirectTo = returnUrl;
        sessionStorage.removeItem('commander_return_url');
      }
    } catch { /* sessionStorage unavailable */ }

    window.location.href = redirectTo;
  }

  // ── UI ──────────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-[#18191A] flex items-center justify-center p-4">
      <SEOHead
        title="Club Commander - Signing In"
        description="Completing your Club Commander sign-in."
        noindex={true}
      />

      <div className="max-w-sm w-full text-center">
        {/* Logo */}
        <img
          src="/images/club-commander-logo.jpg"
          alt="Club Commander"
          className="w-48 mx-auto mb-8 rounded-lg"
        />

        {status === 'loading' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <Loader2 className="w-10 h-10 animate-spin text-[#1877F2] mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-2">Signing you in…</p>
            <p className="text-[#B0B3B8] text-sm">
              Completing your Smarter.Poker session transfer.
            </p>
          </div>
        )}

        {status === 'success' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <ShieldCheck className="w-10 h-10 text-green-400 mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-2">Signed In!</p>
            <p className="text-[#B0B3B8] text-sm">Redirecting to your dashboard…</p>
          </div>
        )}

        {status === 'error' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <AlertTriangle className="w-10 h-10 text-red-400 mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-3">Sign-In Failed</p>
            <p className="text-[#B0B3B8] text-sm mb-6">{error}</p>
            <a
              href="/commander/login"
              className="block w-full bg-[#1877F2] hover:bg-[#1664d9] text-white font-semibold py-3 px-6 rounded-lg text-center transition-colors"
            >
              Sign In Manually
            </a>
          </div>
        )}

        <p className="text-center text-[#65676B] text-xs mt-6">
          Powered by SMARTER.POKER
        </p>
      </div>
    </div>
  );
}
