/**
 * Commander SSO Landing Page - /auth/sso
 *
 * This page receives the one-time SSO token generated by
 * smarter.poker/api/auth/commander-sso and completes the cross-origin login.
 *
 * Flow:
 *   1. smarter.poker hub redirects here with ?token=<raw>&uid=<userId>
 *   2. This page calls /api/auth/sso-exchange with the token + uid
 *   3. The exchange API verifies hash, marks token used, returns a Supabase
 *      magic-link token that verifyOtp() can consume.
 *   4. completeCommanderLogin() (shared staffSession module) stores the
 *      signed commander_staff + commander_venue in localStorage.
 *   5. Redirect to /commander/dashboard (or the stashed return URL).
 *
 * Security notes:
 *   - Token is single-use (marked used=true in DB on first exchange)
 *   - Token TTL is 5 minutes - stale URLs fail with a clear message
 *   - No sensitive data is in the URL except the random token (no JWT)
 *
 * [2026-09-03] The private completeCommanderLogin copy that lived here was
 * replaced by the shared implementation so /auth/sso and /commander/login can
 * never drift apart again (the login page's copy had gone missing entirely).
 * If the user already holds a valid session on this origin, the one-time
 * token is skipped: nothing to exchange, straight to the dashboard.
 */
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { Loader2, ShieldCheck, AlertTriangle } from 'lucide-react';
import { supabase } from '../../src/lib/supabase';
import SEOHead from '../../src/components/seo/SEOHead';
import { completeCommanderLogin } from '../../src/lib/commander/staffSession';
import { reportLoginFailure } from '../../src/lib/authFlowMonitor';

export default function SSOPage() {
  const router = useRouter();
  const [status, setStatus] = useState('loading'); // 'loading' | 'error' | 'success'
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!router.isReady) return;
    const { token, uid } = router.query;

    async function finish(user, accessToken) {
      const result = await completeCommanderLogin(user, accessToken);
      if (result === true) {
        setStatus('success');
        return true;
      }
      reportLoginFailure('sso', result?.error || 'completion failed', { status: result?.status });
      setError(result?.error || 'No active Club Commander subscription found for this account. Please sign up.');
      setStatus('error');
      return false;
    }

    async function exchangeToken() {
      try {
        // Already signed in on this origin (e.g. the user re-opened an old
        // SSO link, or two tabs raced)? Nothing to exchange.
        try {
          const { data: { session } } = await supabase.auth.getSession();
          if (session?.user && (!uid || session.user.id === uid)) {
            await finish(session.user, session.access_token);
            return;
          }
        } catch { /* fall through to the token exchange */ }

        if (!token || !uid) {
          setError('Invalid SSO link. Please sign in manually.');
          setStatus('error');
          return;
        }

        // Exchange the one-time token for a Supabase session
        const res = await fetch('/api/auth/sso-exchange', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ token, uid }),
        });

        const data = await res.json().catch(() => ({}));

        if (!res.ok || !data.token) {
          setError(data.error || 'SSO failed. The link may have expired. Please sign in again.');
          setStatus('error');
          return;
        }

        // Verify the OTP (magic-link type) to get a real Supabase session
        const { data: sessionData, error: otpError } = await supabase.auth.verifyOtp({
          email: data.email,
          token: data.token,
          type: data.type || 'magiclink',
        });

        if (otpError || !sessionData?.session) {
          setError('Failed to restore session. Please sign in manually.');
          setStatus('error');
          return;
        }

        const user = sessionData.session.user;
        const accessToken = sessionData.session.access_token;

        if (!user) {
          setError('Session could not be verified. Please sign in manually.');
          setStatus('error');
          return;
        }

        // Same subscription check + signed staff session as the login page
        await finish(user, accessToken);
      } catch (err) {
        console.error('[SSO] Exchange error:', err);
        reportLoginFailure('sso', err);
        setError('An error occurred during sign-in. Please try again.');
        setStatus('error');
      }
    }

    exchangeToken();
  }, [router.isReady, router.query]); // eslint-disable-line react-hooks/exhaustive-deps

  // -- UI ----------------------------------------------------------------
  return (
    <div className="min-h-screen bg-[#18191A] flex items-center justify-center p-4">
      <SEOHead
        title="Club Commander - Signing In"
        description="Completing your Club Commander sign-in."
        noindex={true}
      />

      <div className="max-w-sm w-full text-center">
        {/* Logo */}
        <img
          src="/images/club-commander-logo.jpg"
          alt="Club Commander"
          className="w-48 mx-auto mb-8 rounded-lg"
        />

        {status === 'loading' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <Loader2 className="w-10 h-10 animate-spin text-[#1877F2] mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-2">Signing you in…</p>
            <p className="text-[#B0B3B8] text-sm">
              Completing your Smarter.Poker session transfer.
            </p>
          </div>
        )}

        {status === 'success' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <ShieldCheck className="w-10 h-10 text-green-400 mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-2">Signed In!</p>
            <p className="text-[#B0B3B8] text-sm">Redirecting to your dashboard…</p>
          </div>
        )}

        {status === 'error' && (
          <div className="bg-[#242526] rounded-xl p-8 border border-[#3A3B3C]">
            <AlertTriangle className="w-10 h-10 text-red-400 mx-auto mb-4" />
            <p className="text-[#E4E6EB] font-semibold text-lg mb-3">Sign-In Failed</p>
            <p className="text-[#B0B3B8] text-sm mb-6">{error}</p>
            <a
              href="/commander/login"
              className="block w-full bg-[#1877F2] hover:bg-[#1664d9] text-white font-semibold py-3 px-6 rounded-lg text-center transition-colors"
            >
              Sign In Manually
            </a>
          </div>
        )}

        <p className="text-center text-[#65676B] text-xs mt-6">
          Powered by SMARTER.POKER
        </p>
      </div>
    </div>
  );
}
